# do not make repository clone cheap: interfers with VCS-based version determination
shallow_clone: false

# turn of support for MS project build support (not needed)
build: off

environment:
  # we pin hatch's data file to make it easy to cache it
  HATCH_DATA_DIR: /home/appveyor/hatch-data-dir
  # same for pip
  PIP_CACHE: /home/appveyor/.cache/pip
  matrix:
    - job_name: test-win
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      # Python version specification is non-standard on windows
      PY: 3.12
      HATCH_DATA_DIR: C:\hatch-data-dir
      PIP_CACHE: C:\Users\appveyor\AppData\Local\pip\Cache
      # make hatch use uv as an installer
      HATCH_ENV_TYPE_VIRTUAL_UV_PATH: C:\Users\appveyor\.local\bin\uv.exe


# only run the CI if there are code or tooling changes
only_commits:
  files:
    - datalad_core/
    - tools/
    - pyproject.toml
    - .appveyor.yml

# job-specific configurations
for:
  - matrix:
      only:
        - job_name: test-win
    cache:
      # pip cache
      - "%PIP_CACHE% -> .appveyor.yml"
      # hatch-managed python versions
      - "%HATCH_DATA_DIR%\\env\\virtual\\.pythons -> pyproject.toml"

    # init cannot use any components from the repo, because it runs prior to
    # cloning it
    init:
      # uv is placed here
      - cmd: echo %PATH%
      - cmd: "set PATH=C:\\Program Files\\Git\\cmd;C:\\Windows\\system32;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Windows\\System32\\OpenSSH;C:\\Program Files\\PowerShell\\7;C:\\Program Files\\7-Zip;C:\\Program Files\\Git\\usr\\bin"
      - cmd: "set PATH=C:\\Users\\appveyor\\.local\\bin;%PATH%"
      - cmd: powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"
      - cmd: uv python list
      # remove windows 260-char limit on path names
      - ps: Set-Itemproperty -path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name LongPathsEnabled -value 1
      # enable developer mode on windows
      # this should enable mklink without admin privileges, but it doesn't seem to work
      #- ps: tools\ci\appveyor_enable_windevmode.ps1
      # enable RDP access on windows (RDP password is in appveyor project config)
      # this is relatively expensive (1-2min), but very convenient to jump into any build at any time
      #- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
      # Scratch space
      - cmd: md C:\DLTMP
      # and use that scratch space to get short paths in test repos
      # (avoiding length-limits as much as possible)
      - cmd: "set TMP=C:\\DLTMP"
      - cmd: "set TEMP=C:\\DLTMP"

    install:
      # place a debug setup helper at a convenient location
      - cmd: copy tools\appveyor\env_setup.bat C:\\datalad_debug.bat

    test_script:
      #- cmd: hatch run hatch-test.py3.13:python -c "import sys; print(sys.version); import platform; print(sys.executable); print(platform.platform()); print(platform.architecture()); from pathlib import Path; from pprint import pprint; pprint(list(Path(sys.executable).parent.glob('*')))"
      - cmd: hatch test -s
      - cmd: hatch test --cover --doctest-modules --durations 10

    after_test:
      - cmd: coverage xml
      - cmd: codecovcli --auto-load-params-from AppVeyor upload-process -n "appveyor-%APPVEYOR_JOB_NAME%" --disable-search -f coverage.xml'

    on_finish:
      # conditionally block the exit of a CI run for direct debugging
      - ps: while ((Test-Path "C:\Users\\appveyor\\Desktop\\BLOCK.txt")) { Start-Sleep 5 }


#
# ALL TEST RUNS
#
build_script:
  - uv tool install hatch
  #- uv tool install codecov-cli
  - hatch run python -V -V

after_build:
  # Identity setup
  - git config --global user.email "test@appveyor.land"
  - git config --global user.name "Appveyor Almighty"
